name: Test

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      CARGO_INCREMENTAL: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: chetan/git-restore-mtime-action@v1.0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest" # "v0.9.1"
      - run: cargo check
      - run: pnpm install
      - run: pnpm build
